services:
  prometheus:
    image: prom/prometheus:latest
    container_name: shortlink-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: shortlink-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./docker/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./docker/dashboards:/etc/grafana/provisioning/dashboards
